#!/usr/bin/env python3
"""Build a Devpost-ready WitnessReplay submission bundle."""

from __future__ import annotations

import argparse
import json
import shutil
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPOSITORY_URL = "https://github.com/gil906/witnessreplay"
DEVPOST_URL = "https://devpost.com/software/witnessreplay"
BUNDLE_NAME = "witnessreplay-devpost-submission"
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT / "dist" / "devpost"


@dataclass(frozen=True)
class BundleFile:
    source: str
    destination: str
    description: str


BUNDLE_FILES = [
    BundleFile("README.md", "README.md", "Project README with setup and challenge links"),
    BundleFile("docs/devpost/submission-summary.md", "submission-summary.md", "Formatted submission summary"),
    BundleFile("docs/devpost/submission-summary.txt", "submission-summary.txt", "Paste-friendly submission summary"),
    BundleFile("docs/devpost/google-cloud-proof.md", "google-cloud-proof.md", "Google Cloud proof guide"),
    BundleFile("docs/devpost/submission-checklist.md", "submission-checklist.md", "Submission checklist"),
    BundleFile("docs/devpost/architecture-diagram.svg", "architecture-diagram.svg", "Uploadable architecture diagram"),
    BundleFile("docs/ARCHITECTURE.md", "reference/ARCHITECTURE.md", "Detailed architecture reference"),
    BundleFile("deploy/cloudbuild.yaml", "reference/cloudbuild.yaml", "Cloud Build deployment config"),
    BundleFile("deploy/terraform/main.tf", "reference/terraform-main.tf", "Terraform Google Cloud infrastructure"),
    BundleFile("backend/requirements.txt", "reference/backend-requirements.txt", "Backend dependency list"),
    BundleFile("backend/app/services/firestore.py", "reference/firestore.py", "Firestore integration"),
    BundleFile("backend/app/services/storage.py", "reference/storage.py", "Cloud Storage integration"),
]


def build_bundle(output_dir: Path) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    bundle_dir = output_dir / BUNDLE_NAME
    zip_path = output_dir / f"{BUNDLE_NAME}.zip"

    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    if zip_path.exists():
        zip_path.unlink()

    bundle_dir.mkdir(parents=True, exist_ok=True)
    copied_files = []

    for bundle_file in BUNDLE_FILES:
        source_path = ROOT / bundle_file.source
        if not source_path.exists():
            raise FileNotFoundError(f"Missing bundle input: {source_path}")

        destination_path = bundle_dir / bundle_file.destination
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)
        copied_files.append(
            {
                "source": bundle_file.source,
                "destination": bundle_file.destination,
                "description": bundle_file.description,
                "bytes": destination_path.stat().st_size,
            }
        )

    notes_path = bundle_dir / "bundle-notes.txt"
    notes_path.write_text(
        "\n".join(
            [
                "WitnessReplay Devpost bundle",
                "===========================",
                "",
                f"Repository: {REPOSITORY_URL}",
                f"Devpost page: {DEVPOST_URL}",
                "",
                "Recommended usage:",
                "- Paste submission-summary.txt into the Devpost text description field.",
                "- Upload architecture-diagram.svg to the file upload or image carousel.",
                "- Use the GitHub URL of google-cloud-proof.md as the Google Cloud proof link.",
                "- Use README.md for spin-up instructions and repo overview.",
                "",
                "Generated by tools/export_devpost_bundle.py",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    manifest_path = bundle_dir / "bundle-manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "bundle_name": BUNDLE_NAME,
                "generated_at": datetime.now(timezone.utc).isoformat(),
                "repository_url": REPOSITORY_URL,
                "devpost_url": DEVPOST_URL,
                "files": copied_files,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(bundle_dir.rglob("*")):
            if path.is_file():
                archive.write(path, arcname=f"{BUNDLE_NAME}/{path.relative_to(bundle_dir)}")

    return bundle_dir, zip_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="Directory where the unzipped and zipped bundle should be written.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser().resolve()
    bundle_dir, zip_path = build_bundle(output_dir)
    print(f"Created bundle directory: {bundle_dir}")
    print(f"Created zip archive:    {zip_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
